### ISSUE TITLE
healpy.query_polygon returns incorrect area for RING

### ISSUE THREAD

**Issue by FurenDeng** [healpy/healpy#904] opened 2024-02-22 09:31 UTC
Hello, I found the pixels returned by healpy.query_polygon is not incorrect for some specific input vectors. The code to produce the incorrect result is below (for healpy version 1.14.0)
```python
import numpy as np
import healpy as hp
from matplotlib import pyplot as plt

nside = 128
nest=False
ipix = hp.query_polygon(nside, np.array([np.array([ 0.93244391, -0.03597633,  0.3595192 ]), np.array([ 0.84225271, -0.03597633,  0.53788109]), np.array([0.84225271, 0.03597633, 0.53788109]), np.array([0.93244391, 0.03597633, 0.3595192 ])]), nest=nest)
skymap = np.zeros(hp.nside2npix(nside), dtype=np.float64)
np.add.at(skymap, ipix, 1.0)
#hp.mollview(skymap)
hp.cartview(skymap, lonra=[-10, 10], latra=[17, 54], nest=nest)
plt.show()
``` 
and the figure is attached below. The figure shows that pixels with lon=0 is not selected. This issue only exist for RING and if set `nest=True`, the result is correct. The incorrect results also appear for areas centered at lon=90, 180 and 270.
![image](https://github.com/healpy/healpy/assets/43858558/5f0cbacd-1b20-47de-b4d8-69ddab3f7c16)

**Comment by mreineck** [comment] 2024-02-22 10:06
Thanks a lot for the report! This looks like something in the C++ code, and it must be *really* old ...
I'll see what I can do!

**Comment by mreineck** [comment] 2024-02-22 11:07
I have a tentative fix; this will have to go into the upstream `Healpix` repository, so I fear it will only become usable with the next `healpy` release.

**Comment by mreineck** [comment] 2024-02-22 17:56
Personally I wouldn't mind moving at all ... but I'm only committing to the Healpix repo about once per year.

@hivon, what's your opinion?

**Comment by mreineck** [comment] 2024-02-23 10:27
Switching to a `ducc0` backend is of course also still an option, and probably will happen sooner or later. It's just a question when that should happen. From my point of view, the earlier the better, but I cannot do all the necessary work.

**Comment by zonca** [comment] 2024-03-05 01:49
@mreineck do you confirm this is fixed in HEALPIX C++?
if so I'll get it into #914

**Comment by mreineck** [comment] 2024-03-05 08:32
My (unfortunately non-automated) tests showed that the stripe in the image above is gone, and unit tests show no regression. Independent confirmation would be even better of course.

**Comment by zonca** [comment] 2024-04-18 16:10
ok, this should be fixed when we updated the C++ code, if not please reopen

**Closed by zonca** 2024-04-18 16:10 UTC
