### ISSUE TITLE
permissions on install-sh not correct

### ISSUE THREAD

**Issue by beckermr** [healpy/healpy#221] opened 2015-01-16 21:32 UTC
I have had build issues. Doing this fixed it
```
chmod u+x /path/to/source/healpy-1.8.3/healpixsubmodule/src/cxx/autotools/install-sh
```

**Comment by lpsinger** [comment] 2015-01-16 21:38
This may be a duplicate of #154. Old versions of `pip` had bugs in which they corrupted permissions (see https://github.com/pypa/pip/issues/1133) which are now fixed. Are you sure that you have a recent version of `pip`?

**Comment by beckermr** [comment] 2015-01-16 22:21
pip 6.0.6 from /usr/local/lib/python2.7/site-packages (python 2.7)

**Comment by defjaf** [comment] 2015-01-17 01:16
I am seeing this problem too, trying to install 1.8.3 via `pip install -U healpy`:

        make: /private/var/folders/bk/zdhpxqj14y5fzcvlpybb4b640000gn/T/pip-build-GUM9Y0/healpy/healpixsubmodule/src/cxx/autotools/install-sh: Permission denied

1.8.2. worked fine, but note that I also just installed a new `setuptools (12.0.1)`. Using the very latest `pip`:

    pip 6.0.6 from /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (python 2.7)


Andrew

**Comment by zonca** [comment] 2015-01-17 03:18
Try with 1.8.4 and please reopen the issue if this is not fixed.

**Comment by lpsinger** [comment] 2015-01-17 05:00
The permissions on `install-sh` are actually incorrect in the PyPI tarball:
 
   $ wget https://pypi.python.org/packages/source/h/healpy/healpy-1.8.4.tar.gz && tar -xzf healpy-1.8.4.tar.gz && ls -l healpy-1.8.4/healpixsubmodule/src/cxx/autotools/install-sh
    -rw-r--r--  1 ...  wheel  13663 Jan 13 13:11 healpy-1.8.4/healpixsubmodule/src/cxx/autotools/install-sh

But if I build my own source tarball, the permissions are correct:

    $ python setup.py sdist && cd dist && tar -xzf healpy-1.8.4.tar.gz && ls -l healpy-1.8.4/healpixsubmodule/src/cxx/autotools/install-sh
    ...
    -rwxr-xr-x  1 ...  staff  13997 Jan 13 11:31 healpy-1.8.4/healpixsubmodule/src/cxx/autotools/install-sh

@zonca, can you check if this file has the right permissions in your source tree? If it does, can you tell us what your umask is? For instance, mine is

    $ umask
    0022

**Comment by zonca** [comment] 2015-01-17 05:22
my bad I needed to run a `git clean`, try again with 1.8.4

**Closed by zonca** 2015-01-17 05:22 UTC
