### ISSUE TITLE
projaxes help contains (apparently) all of matplotlib.axes help (4.6 MB)

### ISSUE THREAD

**Issue by athornton** [healpy/healpy#449] opened 2018-05-31 18:53 UTC
`help(healpy.projaxes)` gives far, far too much information to be useful.  It also overwhelms the Jupyter Notebook's default IOPub data rate.

I suspect this is a bug and you don't really mean to be printing 4-1/2 MB of help when you ask for the projaxes docstring.  You probably want something much more like https://healpy.readthedocs.io/en/1.9.1/healpy_projaxes.html

I wrote the following to capture `help(healpy.projaxes)`:

```
#!/bin/env python

import healpy as hp

# (https://stackoverflow.com/questions/2654834/capturing-stdout-within-the-same-process-in-python/3113913#3113913)

import sys
import io
import contextlib


class Data(object):
    pass


@contextlib.contextmanager
def capture_stdout():
    old = sys.stdout
    capturer = io.StringIO()
    sys.stdout = capturer
    data = Data()
    yield data
    sys.stdout = old
    data.result = capturer.getvalue()

with capture_stdout() as capture:
    help(hp.projaxes)

helpstr = capture.result
with open("help.out", "w") as f:
    f.write(helpstr)
print("Help string is %d characters long and begins with:" % len(helpstr))
print(helpstr[:1200])
print("\n****\nAnd ends with:")
print(helpstr[-1200:])
```

When run, this yields:

```
Help string is 4689326 characters long and begins with:
Help on module healpy.projaxes in healpy:

NAME
    healpy.projaxes

DESCRIPTION
    #  This file is part of Healpy.
    #
    #  Healpy is free software; you can redistribute it and/or modify
    #  it under the terms of the GNU General Public License as published by
    #  the Free Software Foundation; either version 2 of the License, or
    #  (at your option) any later version.
    #
    #  Healpy is distributed in the hope that it will be useful,
    #  but WITHOUT ANY WARRANTY; without even the implied warranty of
    #  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    #  GNU General Public License for more details.
    #
    #  You should have received a copy of the GNU General Public License
    #  along with Healpy; if not, write to the Free Software
    #  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
    #
    #  For more information about Healpy, see http://code.google.com/p/healpy
    #

CLASSES
    matplotlib.axes._axes.Axes(matplotlib.axes._base._AxesBase)
        SphericalProjAxes
            AzimuthalAxes
                HpxAzimuthalAxes
            CartesianAxes
                HpxCartesianAxes
            GnomonicAxes

****
And ends with:
  |      `x` and `y` sticky edge lists.
     |
     |      When performing autoscaling, if a data limit coincides with a value in
     |      the corresponding sticky_edges list, then no margin will be added--the
     |      view limit "sticks" to the edge. A typical usecase is histograms,
     |      where one usually expects no margin on the bottom edge (0) of the
     |      histogram.
     |
     |      This attribute cannot be assigned to; however, the `x` and `y` lists
     |      can be modified in place as needed.
     |
     |      Examples
     |      --------
     |
     |      >>> artist.sticky_edges.x[:] = (xmin, xmax)
     |      >>> artist.sticky_edges.y[:] = (ymin, ymax)
     |
     |  ----------------------------------------------------------------------
     |  Data and other attributes inherited from matplotlib.artist.Artist:
     |
     |  zorder = 0

FUNCTIONS
    create_colormap(cmap)

    get_color_table(vmin, vmax, val, cmap=None, norm=None)

DATA
    UNSEEN = -1.6375e+30
    dtor = 0.017453292519943295
    pi = 3.141592653589793

FILE
    /Users/adam/Documents/src/Venvs/healpy/lib/python3.6/site-packages/healpy/projaxes.py
```

**Comment by zonca** [comment] 2018-06-02 08:43
Thanks, I reproduced this on my machine, but I've no idea why this happens, do you have any suggestion?

**Comment by zonca** [comment] 2018-06-02 09:53
it looks like this is what happens if you subclass `matplotlib.axes.Axes`, the same thing happens with this simple module:

```
import matplotlib.axes

class MySubclass(matplotlib.axes.Axes):
    pass
```

**Comment by zonca** [comment] 2018-06-02 09:59
it looks like this is caused by "Methods inherited from matplotlib.axes._axes.Axes:" listing, it would be nice to only list the method name instead of the full docstring, but I don't know how to modify this.

**Comment by athornton** [comment] 2018-06-02 19:55
I found it baffling too.  If there had been an obvious-to-me fix, the issue would have come with a PR.

**Comment by zonca** [comment] 2018-06-03 20:00
Tried to ask on StackOverflow https://stackoverflow.com/questions/50670470/suppress-metds-inherited-by-base-class-in-subclass-docstring

**Comment by zonca** [comment] 2018-06-05 19:43
it looks like there is no way to fix this, I'll close the issue...

**Closed by zonca** 2018-06-05 19:43 UTC

**Comment by JulienPeloton** [comment] 2018-06-05 20:36
Hi all,

This is definitely not in my top-10 best practices, but you could use this trick to remove the unwanted doc:

```python
## Grab the methods from the original class
method_list = [func for func in dir(mymodule.MySubclass) if callable(getattr(mymodule.MySubclass, func))]

## Remove doc for methods
for el in method_list:
  ## Do not touch _ClassName
  if ("_" not in el[0:2]):
    original_method = getattr(mymodule.MySubclass, el)
    setattr(original_method, "__doc__", "")
  else:
   pass
```

In this case, only the declarations of methods will be kept. 
If you worry about the docstrings, then the final size should be much lower!

**Comment by zonca** [comment] 2018-06-06 20:58
thanks @JulienPeloton 
it is definitely a possibility, but, I'd rather have the issue of large docstrings than have this code run at every import. 

@athornton what do you think about this?
