### ISSUE TITLE
Significant error in the spatial derivatives of a map

### ISSUE THREAD

**Issue by javicarron** [healpy/healpy#610] opened 2020-04-30 13:29 UTC
I am using the `hp.alm2map_der1()` function to calculate the spatial derivatives of some maps. The horizontal (longitude, phi) direction seems to work fine, but the vertical (latitude, theta) direction seems to have errors.

I try both the first and second derivatives on an example map described by cos(phi)+sin(2*theta):

```import numpy as np
import healpy as hp

nside = 512
theta, phi = hp.pix2ang(nside, np.arange(12 * nside ** 2))

good_area = (theta>0.7) * (theta<(np.pi-0.7))   #Cut the poles for better visualization
def see_diff(map1, map2, title):
    maxim = np.max(map2[good_area])
    minim = np.min(map2[good_area])
    fig, axs = plt.subplots(1,3, figsize=(30,10))
    plt.sca(axs[0])
    hp.mollview(map1, fig=fig.number, title=f'Computed {title}', max=maxim, min=minim, hold=True)
    plt.sca(axs[1])
    hp.mollview(map2, fig=fig.number, title=f'Theoretical {title}', max=maxim, min=minim, hold=True)
    plt.sca(axs[2])
    hp.mollview(map1 - map2, fig=fig.number, title=f'Difference in {title}', hold=True)
    
    
example_map = np.cos(phi)+np.sin(2*theta)

alm_map = hp.map2alm(example_map)
_, d_t, d_p = hp.alm2map_der1(alm_map, nside)
d_p = d_p*np.sin(theta)   # To remove the normalization

alm_t = hp.map2alm(d_t)
_, d_tt, d_tp =hp.alm2map_der1(alm_t, nside)
d_tp = d_tp*np.sin(theta)   # To remove the normalization

see_diff(d_p, -np.sin(phi), 'd_p')
see_diff(d_t, 2*np.cos(2*theta), 'd_t')
see_diff(d_tp, np.zeros_like(theta), 'd_tp')
see_diff(d_tt, -np.cos(phi), 'd_tt')
```

This code produces the following images (note that the scale is the same in the first two columns and different in the "differences" column)
![d_p](https://user-images.githubusercontent.com/25009611/80714631-7606d000-8af5-11ea-8d8f-a42871c87f21.png)
![d_t](https://user-images.githubusercontent.com/25009611/80714645-7b641a80-8af5-11ea-8c4b-ae79a9ed1769.png)
![d_tp](https://user-images.githubusercontent.com/25009611/80714651-7f903800-8af5-11ea-9328-5282e83f1e4c.png)
![d_tt](https://user-images.githubusercontent.com/25009611/80714662-828b2880-8af5-11ea-8cde-2094d9d3b049.png)

With the first vertical derivatives it can be seen that some bands are produced, which is accentuated in the second derivatives. I have tried with different values of `lmax` and different maps, but it did not improve the output. Is there a better way to obtain the derivatives?

PS: I guess the derivatives are calculated in harmonic space but I could not track the code where this is performed. I do not know if there is a way to implement it in pixel space or if the result can be improved in harmonic space (if I remember correctly the formula is closed but it involved complex maps).

**Comment by mreineck** [comment] 2020-04-30 13:56
I think the problem is that your input map is not band limited. The `sin(2*theta)` term results in a cusp at both poles, and this means that already the `alm_map = hp.map2alm(example_map)` results in a_lm that are not a faithful harmonic representation of the spatial function. As a consequence the derivatives will also be inaccurate.
I'm pretty sure that you will get fairly accurate derivatives if you change the theta dependency from `sin(2*theta)` to `cos(2*theta)`.

**Comment by javicarron** [comment] 2020-04-30 15:52
Thank you for the reply. Indeed the example was not band limited, that makes sense. I retried using your suggestion `example_map = np.cos(phi)+np.cos(2*theta)` but I run into the same issue:

```
see_diff(d_t, -2*np.sin(2*theta), 'd_t')
see_diff(d_tt, -4.*np.cos(2.*theta), 'd_tt')
```
![d_t_2](https://user-images.githubusercontent.com/25009611/80730615-14049580-8b0a-11ea-8760-a350a8e71c2f.png)
![d_tt_2](https://user-images.githubusercontent.com/25009611/80730623-1666ef80-8b0a-11ea-8920-ae75cb7d6790.png)

I also tried with a more realistic map I am analyzing and the effect is not as severe, but some residual effect can be clearly seen. I do not know if there is any way to mitigate this. 
For example, in the same scale, the original map and the second theta derivative:
![original](https://user-images.githubusercontent.com/25009611/80731253-f2f07480-8b0a-11ea-9556-b1ef81725592.png)
![hess_tt](https://user-images.githubusercontent.com/25009611/80731259-f552ce80-8b0a-11ea-817a-888addb5cb43.png)

**Comment by mreineck** [comment] 2020-04-30 16:03
If you are still seeing this with a band limited map, it could also be caused by insufficient accuracy in the `map2alm` call. Can you try if things improve when you use iterative analysis or weights in `map2alm`? Or if you subtract the map monopole?

In general I'm not totally sure whether the computation of derivatives in harmonic space is very helpful in situations where the original function is defined in position space. I think (but I'm not sure) that this may have been intended for generating derivative maps for a_lm that were generated from a synthetic power spectrum.

**Comment by javicarron** [comment] 2020-05-01 18:21
Thank you for the comment. With respect to the first paragraph, I have tried the same procedure but (separately) with ´use_weights=True´, ´use_pixel_weights=True´, ´datapath=...´.  For this last one, I have downloaded the data from [https://github.com/healpy/healpy-data](https://github.com/healpy/healpy-data) but delving into the source code, I think it is actually the default (and the results are indeed the same). It is not clear to me the theoretical difference from the different weights, could I ask for a pointer to a reference?
The results can be seen here (the last plot is just the standard deviation of each map, calculated in pixel space, a rough proxy of the distortion):
![d_tts](https://user-images.githubusercontent.com/25009611/80830170-cd399d00-8be8-11ea-8478-af5a6aa632a8.png)
So playing with the weights and iterations can indeed reduce the impact of the effect.


About the second paragraph, I agree that the computation of the derivatives in harmonic space is definitely not ideal in my case. I would rather use something pixel-based. Unfortunately, the pixel pattern of the HealPix scheme makes it quite difficult to code (for me). Do you happen to be aware of someone that has faced this before?

**Comment by mreineck** [comment] 2020-05-04 08:06
The problem with pixel weights is that they only really work when `lmax<1.5*nside` in `map2alm`... another situation where default values (`map2alm` sets`lmax=3*nside-1` by default) do more harm than good.

Hmm, perhaps that's the solution after all ... can you try explicitly setting `lmax` to `int(1.5*nside)`?

Concerning the weights: as far as I know, there is no published reference on the ring weights, but I'd be happy to be corrected!
The pixel weights are described here: https://www-user.tu-chemnitz.de/~potts/paper/quadgewS2.pdf

I'm not aware of any software that computes the derivatives directly on Healpix maps ... but at least derivatives with respect to phi should be fairly straightforward.

**Comment by zonca** [comment] 2020-06-05 21:22
no more feedback, closing this

**Closed by zonca** 2020-06-05 21:22 UTC
