### ISSUE TITLE
Build healpy in Anaconda on Mac Mavericks "No script named 'pykg-config.py'"

### ISSUE THREAD

**Issue by taldcroft** [healpy/healpy#216] opened 2015-01-10 21:27 UTC
I'm trying to install healpy to Anaconda on Mac Mavericks and running into a problem that appears related to `pykg-config.py`.  Any help would be appreciated.  Below is the abbreviated version of the [full build log](https://gist.github.com/taldcroft/fad8037be3cd6641e6ec) :
```
(ska)neptune$ python setup.py build
pkg-config is not installed, falling back to pykg-config
running build
running build_py
running build_clib
checking if configure script for library 'cfitsio' exists
checking if configure script for library 'healpix_cxx' exists
checking if library 'cfitsio' is installed
Traceback (most recent call last):
  File "/Users/aldcroft/Downloads/healpy-1.8.1/pykg_config.py", line 3, in <module>
    run_script('pykg-config >= 1.2.0', 'pykg-config.py')
  File "/Users/aldcroft/anaconda/envs/ska/lib/python2.7/site-packages/setuptools-11.3.1-py2.7.egg/pkg_resources/__init__.py", line 696, in run_script
  File "/Users/aldcroft/anaconda/envs/ska/lib/python2.7/site-packages/setuptools-11.3.1-py2.7.egg/pkg_resources/__init__.py", line 1606, in run_script
pkg_resources.ResolutionError: No script named 'pykg-config.py'
building library 'cfitsio' from source
/bin/sh /Users/aldcroft/Downloads/healpy-1.8.1/cfitsio/configure --prefix=/Users/aldcroft/Downloads/healpy-1.8.1/build/temp.macosx-10.5-x86_64-2.7 --disable-shared --with-pic --disable-maintainer-mode
configure: WARNING: unrecognized options: --disable-shared, --with-pic, --disable-maintainer-mode
checking build system type... x86_64-apple-darwin13.4.0
checking host system type... x86_64-apple-darwin13.4.0
checking target system type... x86_64-apple-darwin13.4.0
checking for gcc... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether clang accepts -g... yes
checking for clang option to accept ISO C89... none needed
checking for gfortran... no
checking for g95... no
checking for g77... no
checking for f77... no
checking for ifort... no
checking for f95... no
checking for f90... no
checking for xlf... no
checking for cf77... no
checking for gf77... no
checking for af77... no
checking for ncf... no
checking for f2c... no
configure: WARNING: cfitsio: == No acceptable Fortran compiler found in $PATH
configure: cfitsio: == Adding wrapper support for GNU Fortran by default
checking for ar... ar
checking for ranlib... ranlib
checking how to run the C preprocessor... clang -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... rm: conftest.dSYM: is a directory
rm: conftest.dSYM: is a directory
yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking math.h usability... yes
checking math.h presence... yes
checking for math.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking whether clang accepts -arch i386 -arch x86_64... yes
cfitsio: == Using gcc version 4.2.1
checking "whether ftruncate works"... "yes"
checking "whether long long is defined"... "yes"
checking "whether system V style IPC services are supported"... "yes"
checking "do we have flock_t defined in sys/fcntl.h"... "no"
checking "do we have flock_t defined in sys/flock.h"... "no"
checking "do we have union semun defined"... "yes"
checking for library containing gethostbyname... none required
checking for library containing connect... none required
configure: creating ./config.status
config.status: creating Makefile
configure: WARNING: unrecognized options: --disable-shared, --with-pic, --disable-maintainer-mode
configure: creating ./config.status
config.status: creating Makefile
config.status: creating cfitsio.pc
configure: WARNING: unrecognized options: --disable-shared, --with-pic, --disable-maintainer-mode
 
    Congratulations, Makefile update was successful.
    You may want to run "make" now.
 
make install
/bin/cp -a libcfitsio* /Users/aldcroft/Downloads/healpy-1.8.1/build/temp.macosx-10.5-x86_64-2.7/lib
/bin/cp fitsio.h fitsio2.h longnam.h drvrsmem.h /Users/aldcroft/Downloads/healpy-1.8.1/build/temp.macosx-10.5-x86_64-2.7/include
/bin/cp cfitsio.pc /Users/aldcroft/Downloads/healpy-1.8.1/build/temp.macosx-10.5-x86_64-2.7/lib/pkgconfig
Traceback (most recent call last):
  File "/Users/aldcroft/Downloads/healpy-1.8.1/pykg_config.py", line 3, in <module>
    run_script('pykg-config >= 1.2.0', 'pykg-config.py')
  File "/Users/aldcroft/anaconda/envs/ska/lib/python2.7/site-packages/setuptools-11.3.1-py2.7.egg/pkg_resources/__init__.py", line 696, in run_script
  File "/Users/aldcroft/anaconda/envs/ska/lib/python2.7/site-packages/setuptools-11.3.1-py2.7.egg/pkg_resources/__init__.py", line 1606, in run_script
pkg_resources.ResolutionError: No script named 'pykg-config.py'
Traceback (most recent call last):
  File "setup.py", line 445, in <module>
    license='GPLv2'
  File "/Users/aldcroft/anaconda/envs/ska/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/Users/aldcroft/anaconda/envs/ska/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/Users/aldcroft/anaconda/envs/ska/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/aldcroft/anaconda/envs/ska/lib/python2.7/distutils/command/build.py", line 127, in run
    self.run_command(cmd_name)
  File "/Users/aldcroft/anaconda/envs/ska/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/Users/aldcroft/anaconda/envs/ska/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/aldcroft/anaconda/envs/ska/lib/python2.7/distutils/command/build_clib.py", line 116, in run
    self.build_libraries(self.libraries)
  File "setup.py", line 303, in build_libraries
    for key, value in self.build_library(lib_name, **build_info).items():
  File "setup.py", line 243, in build_library
    build_args = self.pkgconfig(pkg_config_name)
  File "setup.py", line 167, in pkgconfig
    args = [token[index:].decode() for token in check_output(cmd, env=self._environ).split()]
  File "setup.py", line 77, in check_output
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('/Users/aldcroft/anaconda/envs/ska/bin/python', '/Users/aldcroft/Downloads/healpy-1.8.1/pykg_config.py', '--cflags-only-I', 'cfitsio')' returned non-zero exit status 1
```

**Comment by lpsinger** [comment] 2015-01-12 15:53
I am unable to reproduce this using Miniconda on Yosemite. I should be able to quickly lay hands on a Mavericks machine to test this.

**Comment by taldcroft** [comment] 2015-01-12 17:44
FWIW I am able to reproduce using miniconda on a different Mavericks machine.  Basically:
```
bash Miniconda-3.7.0-MacOSX-x86_64.sh
export PATH= ...
conda install pip
conda install numpy
pip install healpy
```
This output line strikes me as odd, but maybe it's OK?:
```
   /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: for architecture: x86_64 file: libcfitsio.a(drvrgsiftp.o) has no symbols
```
Then the failure is similar to what I reported earlier but not identical:
```
   Traceback (most recent call last):
    
      File "/private/var/folders/k1/2ktyqf0x2n7_fzvdnvljq2240000gq/T/pip-build-0OXUso/healpy/pykg_config.py", line 3, in <module>
    
        run_script('pykg-config >= 1.2.0', 'pykg-config.py')
    
      File "/Users/aldcroft/tmp/miniconda/lib/python2.7/site-packages/setuptools-11.3.1-py2.7.egg/pkg_resources/__init__.py", line 696, in run_script
    
      File "/Users/aldcroft/tmp/miniconda/lib/python2.7/site-packages/setuptools-11.3.1-py2.7.egg/pkg_resources/__init__.py", line 918, in require

      File "/Users/aldcroft/tmp/miniconda/lib/python2.7/site-packages/setuptools-11.3.1-py2.7.egg/pkg_resources/__init__.py", line 805, in resolve

    pkg_resources.DistributionNotFound: pykg-config>=1.2.0
    
```

**Comment by lpsinger** [comment] 2015-01-12 18:38
Hmmm, still can't reproduce on Mavericks. Exactly what version of Anaconda do you have?

**Comment by lpsinger** [comment] 2015-01-12 18:40
Did you create a new environment by calling `conda create`, or were you working in the default conda environment?

**Comment by taldcroft** [comment] 2015-01-12 18:53
In the second iteration this was a fresh Anaconda from the latest Miniconda 3.7.0 (as shown in my previous comment):
```
weevil$ conda --version
conda 3.7.4
weevil$ conda list
# packages in environment at /Users/aldcroft/tmp/miniconda:
#
conda                     3.7.4                    py27_0    defaults
numpy                     1.9.1                    py27_0    defaults
openssl                   1.0.1k                        0    defaults
pip                       6.0.6                    py27_0    defaults
pycosat                   0.6.1                    py27_0    <unknown>
pyfits                    3.3                       <pip>
python                    2.7.9                         1    defaults
pyyaml                    3.11                     py27_0    <unknown>
readline                  6.2                           2    <unknown>
requests                  2.5.1                    py27_0    defaults
setuptools                11.3.1                   py27_0    defaults
six                       1.9.0                     <pip>
sqlite                    3.8.4.1                       0    <unknown>
tk                        8.5.15                        0    <unknown>
yaml                      0.1.4                         1    <unknown>
zlib                      1.2.8                         0    defaults
```
Notice that `pyfits` and `six` were installed by healpy prior to the failure.

BTW, I normally have `export CC=clang` in my .bash_profile.  I tried again with the default `gcc` but this didn't change anything.

**Comment by taldcroft** [comment] 2015-01-12 18:55
And of course I do not have `pkg-config` installed.

**Comment by lpsinger** [comment] 2015-01-12 19:01
Oh, duh. Both of my test systems have `pkg-config`; that's why I couldn't reproduce it. I removed `pkg-config` and now I can reproduce this on Yosemite.

**Comment by taldcroft** [comment] 2015-01-12 19:02
Progress!  :smile:

**Comment by lpsinger** [comment] 2015-01-12 19:15
I can see that it is obtaining `pykg_config-1.3.0-py2.7.egg`, but it's not finding it when it tries to run it. Probably an issue with canonicalizing the dash to an underscore. Oh, setuptools.

**Comment by lpsinger** [comment] 2015-01-12 22:06
This is likely a duplicate of #214.

**Closed** 2015-01-13 00:09 UTC

**Comment by lpsinger** [comment] 2015-01-13 00:38
@taldcroft, does this work for you now?

**Comment by taldcroft** [comment] 2015-01-13 02:13
Unfortunately I'm seeing a different problem now building from the latest master.  I cloned the repo, then did `git submodule init` and `git submodule update` per the instructions, but eventually get a failure:
```
/Users/aldcroft/git/healpy/healpixsubmodule/src/cxx/autotools/configure: line 16465: syntax error near unexpected token `CFITSIO,'
/Users/aldcroft/git/healpy/healpixsubmodule/src/cxx/autotools/configure: line 16465: `PKG_CHECK_MODULES(CFITSIO, cfitsio, , CFITSIO_LIBS=-lcfitsio)'
Traceback (most recent call last):
  File "setup.py", line 444, in <module>
    license='GPLv2'
  File "/Users/aldcroft/anaconda/envs/test-healpy/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
```
See https://gist.github.com/taldcroft/fad8037be3cd6641e6ec for the full log.

Slightly OT, but the first time I tried I did not have setuptools installed, so no `pkg_resources`.  This generated a confusing error message that Cython was not installed or new enough.  This comes from the snip below that winds up catching an unexpected exception:
```
cython_require = 'Cython >= 0.16'
try:
    pkg_resources.require(cython_require)
    from Cython.Distutils import build_ext
    ext = "pyx"
    extcpp = "pyx"
except:
    # User does not have a sufficiently new version of Cython.
```

**Comment by taldcroft** [comment] 2015-01-13 02:25
BTW, I have the latest versions of `autoconf` and `libtool` installed.

**Comment by lpsinger** [comment] 2015-01-13 14:38
Unfortunately I'm seeing a different problem now building from the latest master. I cloned the repo, then did git submodule init and git submodule update per the instructions, but eventually get a failure:

/Users/aldcroft/git/healpy/healpixsubmodule/src/cxx/autotools/configure: line 16465: syntax error near unexpected token `CFITSIO,'
/Users/aldcroft/git/healpy/healpixsubmodule/src/cxx/autotools/configure: line 16465: `PKG_CHECK_MODULES(CFITSIO, cfitsio, , CFITSIO_LIBS=-lcfitsio)'
Traceback (most recent call last):
  File "setup.py", line 444, in <module>
    license='GPLv2'
  File "/Users/aldcroft/anaconda/envs/test-healpy/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()


See https://gist.github.com/taldcroft/fad8037be3cd6641e6ec for the full log.

This means that the PKG_CHECK_MODULES autoconf macro was not expanded because it was not available. The macro is distributed with pkg-config, not autoconf; you need pkg-config to build Healpy from git. I'll prepare a tarball for you to test.

Slightly OT, but the first time I tried I did not have setuptools installed, so no pkg_resources. This generated a confusing error message that Cython was not installed or new enough. This comes from the snip below that winds up catching an unexpected exception:

cython_require = 'Cython >= 0.16'
try:
    pkg_resources.require(cython_require)
    from Cython.Distutils import build_ext
    ext = "pyx"
    extcpp = "pyx"
except:
    # User does not have a sufficiently new version of Cython.

Odd. The earlier use_setuptools() call should have prevented this.

**Comment by zonca** [comment] 2015-01-13 18:18
ok @lpsinger I released 1.8.2

**Comment by taldcroft** [comment] 2015-01-13 18:29
@lpsinger or @zonca - are you able to pip install the new 1.8.2 release on a Mac that has no `pkg-config` available?  I just tried and it seems to be failing in the same way.
```
(ska)neptune$ pip install healpy
Downloading/unpacking healpy
  Downloading healpy-1.8.2.tar.gz (4.0MB): 4.0MB downloaded

...
    /bin/cp cfitsio.pc /private/var/folders/_3/rmv7z1hx5jggk39p65j0dcxr0000gn/T/pip_build_aldcroft/healpy/build/temp.macosx-10.5-x86_64-2.7/lib/pkgc
onfig
    Traceback (most recent call last):
      File "/private/var/folders/_3/rmv7z1hx5jggk39p65j0dcxr0000gn/T/pip_build_aldcroft/healpy/run_pykg_config.py", line 6, in <module>
        run_script(requirement, 'pykg-config.py')
      File "/Users/aldcroft/anaconda/envs/ska/lib/python2.7/site-packages/setuptools-11.3.1-py2.7.egg/pkg_resources/__init__.py", line 696, in run_script
      File "/Users/aldcroft/anaconda/envs/ska/lib/python2.7/site-packages/setuptools-11.3.1-py2.7.egg/pkg_resources/__init__.py", line 1606, in run_script
    pkg_resources.ResolutionError: No script named 'pykg-config.py'
```

**Comment by lpsinger** [comment] 2015-01-13 18:38
> @lpsinger or @zonca - are you able to pip install the new 1.8.2 release on a Mac that has no pkg-config available?

It worked for me. Would you show us your full build output?

**Comment by taldcroft** [comment] 2015-01-13 18:49
SUCCESS!  :clap:

I made a clean new Anaconda and it installed just fine.  I'll have to figure why it didn't work in my original  environment, maybe an old setuptools or something, but that's not your problem.  Thanks for the help.
