### ISSUE TITLE
Support nside that's not a power of two?

### ISSUE THREAD

**Issue by cdeil** [healpy/healpy#333] opened 2016-04-01 08:33 UTC
Why does healpy only support nside values that are a power of two?

Is it because the use case of other nside values hasn't come up?
Would pull requests removing the `isnsideok` check from functions where it's not needed be welcome?

This question came up when @tburnett tried to move some of his code over to use `healpy` and tried to call `query_disc` with `nside=12`.

I see that [isnsideok](http://healpy.readthedocs.org/en/latest/generated/healpy.pixelfunc.isnsideok.html) is called for many (all?) healpy functions, and checks that `nside` is a power of two (it's docstring should say that!).

Even for something like [nside2npix](http://healpy.readthedocs.org/en/latest/generated/healpy.pixelfunc.nside2npix.html), where it would be trivial to support `nside` that's not a power of 2.

cc @tburnett

**Comment by mreineck** [comment] 2016-04-01 08:50
The problem is probably mostly interface-related...
For ordering scheme NESTED, nside _must_ be a power of 2 - this is one of the fundamental assumptions of this scheme. For RING, all positive values are in principle OK.
Now, functions like isnsideok only take a single "nside" argument. Given the distinction above, it simply cannot give a correct answer based on nside alone.
This means that for full generality the interface of several functions would have to change, and I expect that the demand for non-power-of-two nside values is fairly low. I implemented them in C++ many years ago "because I could", but so far only used them in two or three very specialized circumstances.

**Comment by tburnett** [comment] 2016-04-01 17:12
In the Fermi-LAT environment, I'm using an interface to HEALPix 3.20, from http://healpix.sourceforge.net. The function query_disc is implemented in healpix_base.cc.  That has worked with nside not a power of 2 (of course RING indexing) for more than 8 years, and is required to interpret the pointlike analysis system.

**Comment by zonca** [comment] 2016-04-01 20:32
duplicate of #70 , please continue discussion there.

**Comment by zonca** [comment] 2016-04-01 20:33
no, actually, sorry, this one has more information, let's keep this open!

**Closed** 2017-01-25 07:30 UTC
