### ISSUE TITLE
Three bugs found in healpy

### ISSUE THREAD

**Issue by ioodderskov** [healpy/healpy#272] opened 2015-08-09 08:02 UTC
I have been trying to get familiar with the healpy package by trying out the examples in the tutorial (http://healpy.readthedocs.org/en/1.6.3/tutorial.html), but get several errors when I try to run the code. After discussing the issues with my local python expert and making a few modifications, the code is runnable, but I guess it would be nice to have the problems fixed anyway. Here they are:  

    hp.graticule()	 
    -> ValueError: Unknown format code 'd' for object of type 'float' 
Apparently, a bug was added here: [Commit](https://github.com/healpy/healpy/commit/a2f256fd96fdfafbcf172a2cb599ba57436f8388#diff-	b8da790f60ace5e858903d7adfb6b599R583)

    cl = hp.anafast(wmap_map_I_masked.filled(), lmax=LMAX) 
    -> "TypeError: 'NoneType' object is not callable" 

If the code is run in a dedicated python console, it runs fine, but if it is run several times in the 	same console, the above error appears. Perhaps it is possible to support non-dedicated consoles.

    wmap_map_I_smoothed = hp.smoothing(wmap_map_I, fwhm=60, arcmin=True) 
    -> TypeError: smoothing() got an unexpected keyword argument 'arcmin' 

I guess the smoothing function has been changed since the tutorial was created.

Apart from these three functions, the examples run as expected. 

The data-files referred to in the examples have been downloaded from these locations: 

http://lambda.gsfc.nasa.gov/product/map/dr4/maps_band_r9_i_7yr_get.cfm 
http://lambda.gsfc.nasa.gov/product/map/dr4/masks_get.cfm. 

Healpy (version 1.8.1) has been installed with pip install --user healpy, and upgraded with pip install --user --upgrade healpy.  I am using python version 2.7.6. I know this is not the latest version of healpy, but as far as I can tell, these issues have not been fixed.

**Comment by zonca** [comment] 2015-09-17 15:19
* the bug in `mollview` was already fixed in the master version of `healpy`.
* `arcmin`  in tutorial fixed in 937bb624c660bc19a19e0ac40d46634dc8dd4a0b
* cannot reproduce error in `anafast`, please open a dedicated issue with more information so I can dig deeper

thanks for reporting!

**Closed by zonca** 2015-09-17 15:19 UTC
