### ISSUE TITLE
Breaks with new version of homebrew cfitsio on OSX 10.11.5

### ISSUE THREAD

**Issue by mennthor** [healpy/healpy#348] opened 2016-07-25 16:33 UTC
With the new cfitsio 3.390 from homebrew from 25.7.2016 the libcfitsio seems to be renamed and healpy 1.9.1 crashes with

`ImportError: dlopen(${HOME}/Library/Python/2.7/lib/python/site-packages/healpy/_healpy_sph_transform_lib.so, 2): Library not loaded: /usr/local/opt/cfitsio/lib/libcfitsio.2.dylib`

Reverting to cfitsio 3.370 with `brew switch cfitsio 3.370` seems to quick-fix the problem.

**Comment by lpsinger** [comment] 2016-07-25 21:19
Looks like an issue with homebrew, right?

**Comment by lpsinger** [comment] 2016-07-28 19:29
Closing because this is an issue with Homebrew. Please re-open if you believe it is a Healpy bug.

**Comment by evertrol** [comment] 2016-08-23 08:34
Mind if I re-open this?
I ran into a similar issue on Ubuntu 16.04.

It appears the issue is the CFITSIO shared library that the binary wheel file for healpy links against. It explicitly links to `libcfitsio.so.3` for me. This should probably just be `libcfitsio.so`. 
As per `ldd`:
```bash
ldd /<some-path>/lib/pythonx.y/site-packages/healpy/_sphtools.cpython-35m-x86_64-linux-gnu.so
	linux-vdso.so.1 =>  (0x00007ffc12dd9000)
	libcfitsio.so.3 => not found
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f8719aea000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f87197e0000)
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f87195be000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f87193a8000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8718fde000)
	/lib64/ld-linux-x86-64.so.2 (0x0000562036cbd000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f8718dda000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f8718bbd000)
```

The problem is that cfitsio increments the so name each time there is a backward incompatibility. Of course, the healpy wheel needs to match the proper version to avoid breaking things, but not all systems will have `libcfitsio.so.2`, `libcfitsio.so.3`, `libcfitsio.so.4` etc installed.

Here's the relevant section from the current `fitsio.h`:
```c
#define CFITSIO_SONAME 5

/* the SONAME is incremented in a new release if the binary shared */
/* library (on linux and Mac systems) is not backward compatible */
/* with the previous release of CFITSIO */
```

I can't readily tell whether this is a bad idea from CFITSIO (since the major version is still 3, there really shouldn't be any backward incompatibilities), or that this a problem with the healpy wheel creation.
If healpy doesn't use any exotic CFITSIO features, I'd suggest linking the wheel binary to the less explicit `libcfitsio.so` shared object, which any system will have symlinked to whatever so-name CFITSIO has defined.

<hr>

A temporary work-around for users is to install through pip (don't know about conda) without the wheel:
```bash
pip install healpy --no-binary healpy
```
Possibly with the `--force` and `--upgrade` flags if already installed.
With that, I get:
```
ldd /<some-path>/lib/pythonx.y/site-packages/healpy/_sphtools.cpython-35m-x86_64-linux-gnu.so
	linux-vdso.so.1 =>  (0x00007ffc888a7000)
	libcfitsio.so.2 => /usr/lib/x86_64-linux-gnu/libcfitsio.so.2 (0x00007f851c2ea000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f851bf68000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f851bc5e000)
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f851ba3c000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f851b826000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f851b45c000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f851b242000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f851b025000)
	/lib64/ld-linux-x86-64.so.2 (0x000055960765e000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f851ae20000)
```

**Comment by lpsinger** [comment] 2016-08-25 15:15
> The problem is that cfitsio increments the so name each time there is a backward incompatibility. Of course, the healpy wheel needs to match the proper version to avoid breaking things, but not all systems will have libcfitsio.so.2, libcfitsio.so.3, libcfitsio.so.4 etc installed.

This is very strange. We did not upload any wheels to PyPI, and none are listed there. Is it possible that pip is using a wheel that it built locally and cached on your computer at some point in the past? If that is the case, then `pip install --no-cache-dir healpy` would work just as well.

(Of course it does look like it is time for us to update the bundled cfitsio library, which would trigger a Healpy version number increment and force your computer to build healpy from source anyway.)

> Also,
> 
> apt install python(3)-healpy
> and related may work in some cases, but not for Homebrew or when updating healpy to more recent versions (python3-healpy lists 1.8.1 as its version).

As I write this, the latest version of Healpy is available through apt on Debian stretch (testing) and later as well as Ubuntu yakkety. (In fact, I maintain the package.) Unfortunately, packages do take quite some time to trickle down into the Debian and Ubuntu stable distributions.

On Mac OS, the latest version of Healpy is available through MacPorts, though that does not help you. I'm not a Homebrew user myself, so we are on the lookout for a volunteer to create a Homebrew package for healpy.

**Comment by evertrol** [comment] 2016-08-26 02:39
If there's no wheel pre-built, then this is simply the result of OS upgrades (in particular the CFITSIO library).
The `--no-cache-dir` option may help, but likely not.

What I think happened is that in the original ticket, the OS (well, Homebrew's cfitsio package) was updated, breaking the healpy so-files. 
If healpy was already at it latest version, then `pip install healpy --upgrade` will not help, and the `--force` flag is necessary (but not the `--no-binary` flag, given there's no wheel).

For me on Ubuntu, it was an OS upgrade & update.

Looks like there's not really a culprit, though it could be argued that Homebrew could leave older `libcfitsio.so(.2)` files in place (it does partially, but doesn't link them).

I think as far as a Homebrew package is concerned: there are some packages (numpy/scipy/matplotlib), albeit only for Python 2. But I think the Homebrew point of view would be more to install Python packages through pip.

Hopefully this issue has solutions for other people running into this problem.

**Comment by lpsinger** [comment] 2016-08-26 15:32
Alright, looks like a confusing situation, but not a bug. May I close this again?

**Comment by evertrol** [comment] 2016-08-27 12:51
Yes, close it. "Re-open" was not really what I meant; more to add a bit more explanation to what I think is going on, for reference. As it doesn't really look like a Homebrew issue, and reverting to an older cfitsio doesn't feel as a satisfying solution.

**Comment by lpsinger** [comment] 2016-08-27 19:07
OK, great. Glad that we found a workaround, though.

**Closed by lpsinger** 2016-08-27 19:07 UTC
