### ISSUE TITLE
Ubuntu 17.10 build failure compiling healpix_cxx

### ISSUE THREAD

**Issue by tskisner** [healpy/healpy#432] opened 2018-04-10 14:02 UTC
If I build the 1.11.0 release on Ubuntu 17.10 with python3 and cfitsio installed through apt, I get this error:
```
$ python3 setup.py build
zip_safe flag not set; analyzing archive contents...

Installed /home/kisner/software/src/healpy-1.11.0/.eggs/pytest_runner-4.2-py3.6.egg
running build
running build_py
creating build
creating build/lib.linux-x86_64-3.6
creating build/lib.linux-x86_64-3.6/healpy
copying healpy/__init__.py -> build/lib.linux-x86_64-3.6/healpy
copying healpy/pixelfunc.py -> build/lib.linux-x86_64-3.6/healpy
copying healpy/sphtfunc.py -> build/lib.linux-x86_64-3.6/healpy
copying healpy/visufunc.py -> build/lib.linux-x86_64-3.6/healpy
copying healpy/fitsfunc.py -> build/lib.linux-x86_64-3.6/healpy
copying healpy/projector.py -> build/lib.linux-x86_64-3.6/healpy
copying healpy/rotator.py -> build/lib.linux-x86_64-3.6/healpy
copying healpy/projaxes.py -> build/lib.linux-x86_64-3.6/healpy
copying healpy/version.py -> build/lib.linux-x86_64-3.6/healpy
copying healpy/cookbook.py -> build/lib.linux-x86_64-3.6/healpy
copying healpy/zoomtool.py -> build/lib.linux-x86_64-3.6/healpy
copying healpy/newvisufunc.py -> build/lib.linux-x86_64-3.6/healpy
creating build/lib.linux-x86_64-3.6/healpy/test
copying healpy/test/test_spinfunc.py -> build/lib.linux-x86_64-3.6/healpy/test
copying healpy/test/test_query_disc.py -> build/lib.linux-x86_64-3.6/healpy/test
copying healpy/test/__init__.py -> build/lib.linux-x86_64-3.6/healpy/test
copying healpy/test/test_sphtfunc.py -> build/lib.linux-x86_64-3.6/healpy/test
copying healpy/test/test_pixelfunc.py -> build/lib.linux-x86_64-3.6/healpy/test
copying healpy/test/test_visufunc.py -> build/lib.linux-x86_64-3.6/healpy/test
copying healpy/test/test_fitsfunc.py -> build/lib.linux-x86_64-3.6/healpy/test
creating build/lib.linux-x86_64-3.6/healpy/data
copying healpy/data/weight_ring_n00004.fits -> build/lib.linux-x86_64-3.6/healpy/data
copying healpy/data/pixel_window_n0004.fits -> build/lib.linux-x86_64-3.6/healpy/data
copying healpy/data/weight_ring_n00002.fits -> build/lib.linux-x86_64-3.6/healpy/data
copying healpy/data/pixel_window_n0256.fits -> build/lib.linux-x86_64-3.6/healpy/data
copying healpy/data/weight_ring_n00064.fits -> build/lib.linux-x86_64-3.6/healpy/data
copying healpy/data/pixel_window_n0064.fits -> build/lib.linux-x86_64-3.6/healpy/data
copying healpy/data/pixel_window_n0128.fits -> build/lib.linux-x86_64-3.6/healpy/data
copying healpy/data/pixel_window_n1024.fits -> build/lib.linux-x86_64-3.6/healpy/data
copying healpy/data/pixel_window_n4096.fits -> build/lib.linux-x86_64-3.6/healpy/data
copying healpy/data/weight_ring_n00128.fits -> build/lib.linux-x86_64-3.6/healpy/data
copying healpy/data/weight_ring_n02048.fits -> build/lib.linux-x86_64-3.6/healpy/data
copying healpy/data/weight_ring_n01024.fits -> build/lib.linux-x86_64-3.6/healpy/data
copying healpy/data/weight_ring_n00256.fits -> build/lib.linux-x86_64-3.6/healpy/data
copying healpy/data/weight_ring_n04096.fits -> build/lib.linux-x86_64-3.6/healpy/data
copying healpy/data/pixel_window_n0008.fits -> build/lib.linux-x86_64-3.6/healpy/data
copying healpy/data/pixel_window_n8192.fits -> build/lib.linux-x86_64-3.6/healpy/data
copying healpy/data/weight_ring_n08192.fits -> build/lib.linux-x86_64-3.6/healpy/data
copying healpy/data/pixel_window_n0512.fits -> build/lib.linux-x86_64-3.6/healpy/data
copying healpy/data/weight_ring_n00016.fits -> build/lib.linux-x86_64-3.6/healpy/data
copying healpy/data/weight_ring_n00512.fits -> build/lib.linux-x86_64-3.6/healpy/data
copying healpy/data/pixel_window_n2048.fits -> build/lib.linux-x86_64-3.6/healpy/data
copying healpy/data/pixel_window_n0032.fits -> build/lib.linux-x86_64-3.6/healpy/data
copying healpy/data/weight_ring_n00032.fits -> build/lib.linux-x86_64-3.6/healpy/data
copying healpy/data/weight_ring_n00008.fits -> build/lib.linux-x86_64-3.6/healpy/data
copying healpy/data/pixel_window_n0016.fits -> build/lib.linux-x86_64-3.6/healpy/data
copying healpy/data/pixel_window_n0002.fits -> build/lib.linux-x86_64-3.6/healpy/data
copying healpy/data/totcls.dat -> build/lib.linux-x86_64-3.6/healpy/data
creating build/lib.linux-x86_64-3.6/healpy/test/data
copying healpy/test/data/cl_wmap_band_iqumap_r9_7yr_W_v4_udgraded32_IQU_lmax64_rmmono_3iter.fits -> build/lib.linux-x86_64-3.6/healpy/test/data
copying healpy/test/data/wmap_temperature_analysis_mask_r9_7yr_v4_udgraded32.fits -> build/lib.linux-x86_64-3.6/healpy/test/data
copying healpy/test/data/wmap_band_iqumap_r9_7yr_W_v4_udgraded32_masked_smoothed10deg_fortran.fits -> build/lib.linux-x86_64-3.6/healpy/test/data
copying healpy/test/data/wmap_band_iqumap_r9_7yr_W_v4_udgraded32_masked.fits -> build/lib.linux-x86_64-3.6/healpy/test/data
copying healpy/test/data/gaussbeam_10arcmin_lmax512_pol.fits -> build/lib.linux-x86_64-3.6/healpy/test/data
copying healpy/test/data/cl_wmap_band_iqumap_r9_7yr_W_v4_udgraded32_II_lmax64_rmmono_3iter_nomask.fits -> build/lib.linux-x86_64-3.6/healpy/test/data
copying healpy/test/data/wmap_band_iqumap_r9_7yr_V_v4_udgraded32.fits -> build/lib.linux-x86_64-3.6/healpy/test/data
copying healpy/test/data/cl_wmap_band_iqumap_r9_7yr_W_v4_udgraded32_II_lmax64_rmmono_3iter.fits -> build/lib.linux-x86_64-3.6/healpy/test/data
copying healpy/test/data/wmap_band_iqumap_r9_7yr_W_v4_udgraded32.fits -> build/lib.linux-x86_64-3.6/healpy/test/data
copying healpy/test/data/cl_wmap_band_iqumap_r9_7yr_WVxspec_v4_udgraded32_II_lmax64_rmmono_3iter.fits -> build/lib.linux-x86_64-3.6/healpy/test/data
copying healpy/test/data/map_synfast_seed12345.fits -> build/lib.linux-x86_64-3.6/healpy/test/data
copying healpy/test/data/wmap_band_iqumap_r9_7yr_W_v4_udgraded32_smoothed10deg_fortran.fits -> build/lib.linux-x86_64-3.6/healpy/test/data
copying healpy/test/data/wmap_band_iqumap_r9_7yr_V_v4_udgraded32_masked.fits -> build/lib.linux-x86_64-3.6/healpy/test/data
running build_clib
checking if configure script for library 'cfitsio' exists
checking if configure script for library 'healpix_cxx' exists
checking if library 'cfitsio' is installed
found 'cfitsio' installed, using it
checking if library 'healpix_cxx' is installed
Package healpix_cxx was not found in the pkg-config search path.
Perhaps you should add the directory containing `healpix_cxx.pc'
to the PKG_CONFIG_PATH environment variable
No package 'healpix_cxx' found
building library 'healpix_cxx' from source
creating /home/kisner/software/src/healpy-1.11.0/build/temp.linux-x86_64-3.6
creating /home/kisner/software/src/healpy-1.11.0/build/temp.linux-x86_64-3.6/healpix_cxx
/bin/sh /home/kisner/software/src/healpy-1.11.0/healpixsubmodule/src/cxx/autotools/configure --prefix=/home/kisner/software/src/healpy-1.11.0/build/temp.linux-x86_64-3.6 --disable-shared --with-pic --disable-maintainer-mode
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for style of include used by make... GNU
checking for gcc... x86_64-linux-gnu-gcc -pthread
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/home/kisner/software/src/healpy-1.11.0/build/temp.linux-x86_64-3.6/healpix_cxx':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
Traceback (most recent call last):
  File "setup.py", line 220, in build_library
    build_args = self.pkgconfig(pkg_config_name)
  File "setup.py", line 198, in pkgconfig
    args = [token[index:].decode() for token in check_output(cmd, env=env).split()]
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '('pkg-config', '--cflags-only-I', 'healpix_cxx >= 3.30.0')' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 445, in <module>
    license='GPLv2'
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.6/distutils/command/build_clib.py", line 115, in run
    self.build_libraries(self.libraries)
  File "setup.py", line 337, in build_libraries
    for key, value in self.build_library(lib_name, **build_info).items():
  File "setup.py", line 270, in build_library
    CC=cc, CXX=cxx, CFLAGS=cflags, CXXFLAGS=cxxflags))
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/sh', '/home/kisner/software/src/healpy-1.11.0/healpixsubmodule/src/cxx/autotools/configure', '--prefix=/home/kisner/software/src/healpy-1.11.0/build/temp.linux-x86_64-3.6', '--disable-shared', '--with-pic', '--disable-maintainer-mode']' returned non-zero exit status 1.
```
The config.log from the healpix_cxx build [is attached here](https://github.com/healpy/healpy/files/1894911/config.log).  Also note that I get the same error when installing healpy through pip (which is also running setup.py to compile healpix_cxx).

**Comment by zonca** [comment] 2018-04-10 14:27
Can you please check if it is a duplicate of #430?

Il mar 10 apr 2018, 16:02 Theodore Kisner <notifications@github.com> ha
scritto:

**Comment by zonca** [comment] 2018-04-10 15:26
cannot reproduce this in 16.04,
@mreineck there is an obscure C error `configure: error: cannot run C compiled programs.`, do you have any suggestions?

**Comment by tskisner** [comment] 2018-04-10 15:34
I don't think this is related to #430.  Based on the config.log output (above):
```
configure:3508: checking whether we are cross compiling
configure:3516: x86_64-linux-gnu-gcc -pthread -o conftest -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.6-sXpGnM/python3.6-3.6.3=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security   conftest.c  >&5
conftest.c:13:1: warning: function declaration isn't a prototype [-Wstrict-prototypes]
 main ()
 ^~~~
/usr/bin/ld: /tmp/ccaNNZBn.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
configure:3520: $? = 1
configure:3527: ./conftest
/home/kisner/software/src/healpy-1.11.0/healpixsubmodule/src/cxx/autotools/configure: line 3529: ./conftest: No such file or directory
configure:3531: $? = 127
configure:3538: error: in `/home/kisner/software/src/healpy-1.11.0/build/temp.linux-x86_64-3.6/healpix_cxx':
configure:3540: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
```
It seems like this configure test is linking some object file that was not compiled with -fPIC.  I can try to dig deeper.

**Comment by mreineck** [comment] 2018-04-10 16:38
I agree that this is most likely a missing "-fPIC". However, a standard "configure" run should not encounter such a situation, as far as I understand. Which flags are passed to configure by the healpy build mechanism?

**Comment by tskisner** [comment] 2018-04-10 16:43
From config.log:
```
It was created by healpix_cxx configure 3.30.0, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  $ /home/kisner/software/src/healpy-1.11.0/healpixsubmodule/src/cxx/autotools/configure --prefix=/home/kisner/software/src/healpy-1.11.0/build/temp.linux-x86_64-3.6 --disable-shared --with-pic --disable-maintainer-mode
```

**Comment by mreineck** [comment] 2018-04-10 17:10
Hmm ... I'm by no means an autotools expert, but the combination of "--disable-shared" and "--with-pic" looks fairly special (and probably rarely used) to me. Could this sufficiently confuse configure?

In any case ... the failure occurs within configure, so there is probably nothing we can do about it on the Healpix side of things, right? Unless, of course, our configure.ac is buggy...

**Comment by zonca** [comment] 2018-04-16 09:13
I reproduced this in a 17.10 container, I got it to build (after a lot of attempts...) by running the configure step manually instead of having Python run it. My guess is that running through Python messes up the environment somehow, but I don't know how to fix it.

So:

* try to build and get to the error
* copy the configuration string with all the options, for my case:

        /bin/sh /root/healpy/healpixsubmodule/src/cxx/autotools/configure --prefix=/root/healpy/build/temp.linux-x86_64-3.6 --disable-shared --with-pic --disable-maintainer-mode

* enter the build folder `/root/healpy/healpixsubmodule/src/cxx/autotools/`
* run the configure step above and `make install`
* back to the `healpy` root folder, run the build step again, it should detect that healpix is already built.

**Comment by lpsinger** [comment] 2018-04-16 19:18
> Hmm ... I'm by no means an autotools expert, but the combination of "--disable-shared" and "--with-pic" looks fairly special (and probably rarely used) to me. Could this sufficiently confuse configure?

No, this is intentional: we are telling configure that we want to build a healpix_cxx as a static library.

**Comment by tskisner** [comment] 2018-04-16 21:15
There are multiple ways of installing pre-built packages (APT, conda-forge channel, etc).  This issue was focused on installing healpy from source, which is sometimes needed to get the latest version.  For example the healpy version in 17.10 (and 18.04) is 1.10.x.

Some context:  a couple years ago I had issues installing the healpix_cxx library within healpy on some of the Cray machines at NERSC.  That led me to autotool-ize the install of all packages (https://github.com/tskisner/healpix-autotools), which then allowed better control of the compile options of healpix_cxx and enabled healpy to use that external library.

Healpy has improved a lot in the past couple years (thank you all!), and basically it is the only healpix implementation I use on a regular basis.  Rather than maintain the packaging effort above, I was trying to see if I can just deprecate that healpix-autotools package and use "stock" healpy everywhere.  I tried the build on Ubuntu 17.10 and... opened this issue.

@lpsinger, I downloaded your healpy source package and looked at the debian/rules files, but nothing obvious stands out about why that build works and a standard one does not.

Based on @zonca's test above, it may just be an autotools issue or something about the calling environment.  I'll test along those lines now.

**Comment by tskisner** [comment] 2018-04-16 21:45
Ok, some more clues.  Just forcing the build to use '-fPIC' works:
```
CC=gcc CXX=g++ CFLAGS='-fPIC' CXXFLAGS='-fPIC' python3 setup.py build
```
Also, note that in the debian package build of healpy, the '-flto' option is specified (link time optimization), which forces -fPIC.  So that is why the debian package build works.

Now I'm looking into why the configure option "--with-pic" does not enable -fPIC, even in the case of "--disable-shared".  That combination certainly should be valid from an autotools perspective.

**Comment by tskisner** [comment] 2018-04-16 22:10
Since the healpixsubmodule is just a mirror of the upstream source, I guess that it is beyond the scope of healpy development?  Since just forcing the "-fPIC" flags above works, that seems like an ok workaround for now...

I noticed that setup.py is calling "autoreconf".  That means that your build system files will be dependent on the autotools versions on the user machine (which could be ancient).  

Something to consider:  if you do a "make dist" of the upstream healpix_cxx source and use that instead of a submodule, then the resulting healpy install would never depend on autotools (it would use the pre-generated configure).  You could then do the upstream "make dist" on a machine with the latest autotools and ensure that the build system files are the same for every install.

Feel free to close this issue.  If there is interest in a test case of bundling healpix_cxx differently, I can open a PR as an example.

**Closed** 2019-10-25 20:06 UTC
