### ISSUE TITLE
Installation errors with Canopy 1.5.2 on Mac OSX 10.8.5

### ISSUE THREAD

**Issue by mayurisrao** [healpy/healpy#225] opened 2015-03-02 05:35 UTC
I'm beginning with github, so not sure how to link the file. Hope it works.. 

I'm trying to install HEALPy in Canopy. I tried installing both with pip and from the source. Note that Canopy is my default Python.
The errors I see in both cases are here : https://gist.github.com/2520e4d51a4f185c3cb5.git

It looks like in the case of installation from source, HEALPy seems to look in the wrong directory by default, possibly hardcoded in the install code?
I also tried running 
CXX=g++ python setup.py build 
and
CXX=/usr/bin/clang++ python setup.py build
as suggested in https://github.com/healpy/healpy/issues/211
but it didn't work  but the error looks similar to what I see when I try installing with pip.

In pip install there may be a compilation issue.
Any suggestions? Do you think it might be compiler related? Any help would be greatly appreciated.

**Comment by lpsinger** [comment] 2015-03-02 14:46
> The errors I see in both cases are here : https://gist.github.com/2520e4d51a4f185c3cb5.git

https://gist.github.com/mayurisrao/2520e4d51a4f185c3cb5

**Comment by lpsinger** [comment] 2015-03-02 15:14
I was able to build and install the latest stable source under Canopy 1.5.2 on Mac OS X 10.10.2:

    $ wget https://pypi.python.org/packages/source/h/healpy/healpy-1.8.4.tar.gz
    $ tar -xzf healpy-1.8.4.tar.gz
    $ cd healpy-1.8.4/
    $ ~/Library/Enthought/Canopy_64bit/User/bin/python setup.py install

On the last step, are you sure that Canopy's python interpreter is on your `PATH`? What does `which python` print?

Installing with `pip` worked for me too:

    $ ~/Library/Enthought/Canopy_64bit/User/bin/pip install healpy

**Comment by mayurisrao** [comment] 2015-03-03 03:48
`which python` returns the Canopy path, so that seems okay. 
Both the pip method and source installation still fail. Could this be a C compiling issue? Is there anyway to build all the C libraries first and then install the python package on top?  
The errors I see with source installation are in the gist here 
https://gist.github.com/3f3f302920bbfc18b438.git

I am not sure what the main error is which is causing the instal to fail.

**Comment by lpsinger** [comment] 2015-03-03 04:22
> The errors I see with source installation are in the gist here 
> https://gist.github.com/3f3f302920bbfc18b438.git

That is probably the git clone URL. The URL for viewing this git in a web browser is:
https://gist.github.com/mayurisrao/3f3f302920bbfc18b438

**Comment by lpsinger** [comment] 2015-03-03 04:29
> Both the pip method and source installation still fail. Could this be a C compiling issue?

The issue that you reported with the source build (`You are attempting to install a package to a directory that is not on PYTHONPATH`...) definitely does not have anything to do with the C compiler; it looks like something with your Python path is misconfigured.

The issue that you reported with the `pip` build may be related to the C compiler, but I do not know why it is failing. The immediate cause is definitely that it cannot find a symbol called `kahan_adder`, but this is declared in the HEALPix source code and should be pulled in by the preprocessor. What version of `pip` are you using?

Do you have access to a Mac OS 10.10 machine on which you could test this? As I said, I was able to build from Canopy using both methods on my Yosemite machine.

> Is there anyway to build all the C libraries first and then install the python package on top?

Yes. If you install the autotools-style healpix-cxx package first (http://sourceforge.net/projects/healpix/files/Healpix_3.11/autotools_packages/), then the Healpy build will detect the library with pkg-config and build against it.

**Comment by mayurisrao** [comment] 2015-03-06 05:17
Thanks for your help! I did get Healpy installed and working but here's what I did. I'm not sure what exactly got it working and installed while I had done the exact same things before!!!
First I tried installing HEALPy with macports.. This didn't work as macports complained about deactivated setuptools.. I had to run
```  $ sudo port -f activate py27-setuptools ```
Once this was done I once again ran 
``` $ sudo port install py27-healpy```
This seemed to install a lot of packages (possibly long overdue) but at the last step again failed with an error like this.
Error: org.macports.build for port py27-healpy returned: command execution failed
To report a bug, follow the instructions in the guide:
http://guide.macports.org/#project.tickets
Error: Processing of port py27-healpy failed 
In the meantime I had also changed my PYTHONPATH to explicitly include the 
 ~/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/ 
I think this might have been the main culprit, which I didn't have included all along. I only had 
 /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages 
Ok.. so quick recap.. Activated setuptools with macports.. Changed PYTHONPATH in .bash and ran macports.. 
As a desperate last try I ran 
``` $ sudo ~/Library/Enthought/Canopy_64bit/User/bin/pip install healpy```
and voila!
``` Successfully installed healpy-1.8.4``` 
Of course there are plenty of warnings.. but I imported and ran some HEALPy commands on Canopy and they seem to all work fine! So.. yes, not sure what exactly worked, but it did work.
lpsinger thanks for all your help.

**Comment by lpsinger** [comment] 2015-03-06 15:45
@mayurisrao, I'm glad that your installation works now. I'm closing this issue.

For your information, I want to point out a few possible issues with your Python setup:

> First I tried installing HEALPy with macports.. This didn't work as macports complained about deactivated setuptools.. I had to run
> $ sudo port -f activate py27-setuptools

As far as I can tell, Canopy's Python environment is completely isolated and should not be picking up any Python packages from MacPorts. Since evidently installing a new MacPorts version of setuptools had something to do with your solution, you may have a very strange `PYTHONPATH` setting.

> Once this was done I once again ran 
> $ sudo port install py27-healpy
> This seemed to install a lot of packages (possibly long overdue) but at the last step again failed with an error like this.
> Error: org.macports.build for port py27-healpy returned: command execution failed
> To report a bug, follow the instructions in the guide:
> http://guide.macports.org/#project.tickets
> Error: Processing of port py27-healpy failed

I was able to reinstall Healpy with MacPorts just now, but once again I am on Yosemite and it is possible that you are encountering some new Lion-specific issue.

You should file a MacPorts bug report. I am the MacPorts maintainer for Healpy ;-)

> In the meantime I had also changed my PYTHONPATH to explicitly include the 
> ~/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/ 
> I think this might have been the main culprit, which I didn't have included all along.

Yes, precisely. This is the cause of your original error message from pip (`You are attempting to install a package to a directory that is not on PYTHONPATH`...).

> I only had 
> /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages

OK, although this can be done, be aware that there are likely to be some complications involved in mixing MacPorts and Anaconda packages; this is nothing specific about Healpy.

> As a desperate last try I ran 
> $ sudo ~/Library/Enthought/Canopy_64bit/User/bin/pip install healpy
> and voila!

Beware that your Canopy environment is in your home directory, owned by your ordinary user account, but you have now installed packages into it as `root`. You only need `sudo` if you are installing into a `root`-owned system location (not advised in general).

**Closed by lpsinger** 2015-03-06 15:45 UTC
