### ISSUE TITLE
Unit tests fail on i386

### ISSUE THREAD

**Issue by lpsinger** [healpy/healpy#528] opened 2019-01-19 17:00 UTC
Unit tests fail with healpy 1.12.8 on Debian i386. See [full build log](https://buildd.debian.org/status/fetch.php?pkg=healpy&arch=i386&ver=1.12.8-4&stamp=1547914020&file=log) and excerpt of the most relevant part below.

```
=================================== FAILURES ===================================
______________________ [doctest] healpy.pixelfunc.ang2pix ______________________
440     --------
441     pix2ang, pix2vec, vec2pix
442 
443     Examples
444     --------
445     >>> import healpy as hp
446     >>> hp.ang2pix(16, np.pi/2, 0)
447     1440
448 
449     >>> print(hp.ang2pix(16, [np.pi/2, np.pi/4, np.pi/2, 0, np.pi], [0., np.pi/4, np.pi/2, 0, 0]))
Expected:
    [1440  427 1520    0 3068]
Got:
    [1440  427 1456    0 3068]

/<<PKGBUILDDIR>>/.pybuild/cpython3_3.7_healpy/build/healpy/pixelfunc.py:449: DocTestFailure
________________ [doctest] healpy.pixelfunc.get_interp_weights _________________
1334     array([ 0.25,  0.25,  0.25,  0.25])
1335 
1336     >>> pix, weights = hp.get_interp_weights(1, 0, 90, lonlat=True)
1337     >>> print(pix)
1338     [1 2 3 0]
1339     >>> weights
1340     array([ 0.25,  0.25,  0.25,  0.25])
1341 
1342     >>> pix, weights = hp.get_interp_weights(1, [0, np.pi/2], 0)
1343     >>> print(pix)
Differences (unified diff with -expected +actual):
    @@ -1,4 +1,4 @@
    -[[ 1  4]
    - [ 2  5]
    - [ 3 11]
    - [ 0  8]]
    +[[1 3]
    + [2 0]
    + [3 4]
    + [0 5]]
```

**Comment by zonca** [comment] 2019-01-21 02:39
is this fixed with your latest PR?

**Comment by lpsinger** [comment] 2019-01-21 04:05
No.

**Comment by lpsinger** [comment] 2019-01-21 04:05
But the latest PR did fix the build on all 32-bit platforms *except* i386.

**Comment by lpsinger** [comment] 2019-01-21 20:44
Interesting, the example that fails for ang2pix is theta=pi/2, phi=pi/2. Is that some kind of clue?

**Comment by mreineck** [comment] 2019-01-23 11:11
Yes, that's exactly on a point where four pixels meet. Expecting reproducible results for these angles is a bit optimistic.

**Comment by mreineck** [comment] 2019-01-23 11:12
... and 32bit i386 math is not IEEE conforming.

**Comment by lpsinger** [comment] 2019-01-23 17:02
> ... and 32bit i386 math is not IEEE conforming.

Wait, really? Do you mean that 32 bit floating point math on i386 is not IEEE conforming, or that 64-bit floating point math on the 32-bit i386 platform is not IEEE conforming? I thought that x86 processors are IEEE754 conforming with the exception of those infamously buggy Pentiums back in the day.

I can reproduce this issue on my modern Core i7 machine under an i386 Debian docker image.

**Comment by mreineck** [comment] 2019-01-23 17:13
As far as I know, floating point math in x86 32bit mode (no matter whether in single or double precision) is carried out on the old 80387 floating point coprocessor by default. And this coprocessor is not IEEE-compliant because it has too high-precision (it uses 80bit floats internally). For that reason you don't always get the same results as on a strictly IEEE-conforming architecture.

In any case, I'd argue not to test for reproducibility in such corner cases here. We want to be able to compile Healpix C++ with optimization flags that can lead to slightly different results anyway (e.g. by allowing "x/10" to be replaced by "x*0.1").

**Comment by lpsinger** [comment] 2019-01-24 14:34
OK, I'll prepare a patch to adjust the unit test output. Shifting phi by 1e-15 did the trick:

```
$ python3 -c 'import numpy as np; import healpy as hp; print(hp.ang2pix(16, np.pi/2, np.pi/2+1e-15))'
1520
```

FWIW, adding `-mpc64` to `CFLAGS` and `CXXFLAGS` also worked.

**Comment by mreineck** [comment] 2019-01-24 14:45
We have to revisit this whole test at some point. It also tests North and South poles, which again are exactly on pixel corners.

**Closed** 2019-01-24 20:56 UTC
