### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by cmbant** [healpy/healpy#265] opened 2015-07-03 14:57 UTC
I've tried many configuration of python on NERSC Edison, and  "pip install healpy" does not seem to work, including a fully new clean user anaconda installation. The "pip install healpy" itself appears to run OK (but very quickly).

```
Collecting healpy
Requirement already satisfied (use --upgrade to upgrade): matplotlib in ./anaconda/lib/python2.7/site-packages (from healpy)
Requirement already satisfied (use --upgrade to upgrade): six in ./anaconda/lib/python2.7/site-packages (from healpy)
Requirement already satisfied (use --upgrade to upgrade): astropy in ./anaconda/lib/python2.7/site-packages (from healpy)
Requirement already satisfied (use --upgrade to upgrade): numpy in ./anaconda/lib/python2.7/site-packages (from healpy)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in ./anaconda/lib/python2.7/site-packages (from matplotlib->healpy)
Requirement already satisfied (use --upgrade to upgrade): pytz in ./anaconda/lib/python2.7/site-packages (from matplotlib->healpy)
Requirement already satisfied (use --upgrade to upgrade): pyparsing>=1.5.6 in ./anaconda/lib/python2.7/site-packages (from matplotlib->healpy)
Requirement already satisfied (use --upgrade to upgrade): nose>=0.11.1 in ./anaconda/lib/python2.7/site-packages (from matplotlib->healpy)
Requirement already satisfied (use --upgrade to upgrade): mock in ./anaconda/lib/python2.7/site-packages (from matplotlib->healpy)
Installing collected packages: healpy
Successfully installed healpy-1.8.6
```
`
However you cannot use it, e.g. in ipython

```
In [1]: import healpy
/global/homes/a/aml1005/anaconda/lib/python2.7/site-packages/healpy/sphtfunc.py:42: UserWarning: Warning: cannot import _sphtools module
  warnings.warn('Warning: cannot import _sphtools module')
/global/homes/a/aml1005/anaconda/lib/python2.7/site-packages/healpy/__init__.py:57: UserWarning: Warning: cannot import query disc module
  warnings.warn('Warning: cannot import query disc module')
/global/homes/a/aml1005/anaconda/lib/python2.7/site-packages/healpy/__init__.py:61: UserWarning: Warning: cannot import pixelfunc module
  warnings.warn('Warning: cannot import pixelfunc module')
/global/homes/a/aml1005/anaconda/lib/python2.7/site-packages/healpy/__init__.py:68: UserWarning: Warning: cannot import _sphtools module
  warnings.warn('Warning: cannot import _sphtools module')
```

This may not specifically be a healpy issue, but it would be helpful if the install could give an error message about whatever is failing so the user has something to go on.

**Comment by zonca** [comment] 2015-07-05 20:09
is that the full log of `pip install healpy`? if so can you try with `pip -v install healpy`?

**Comment by zonca** [comment] 2015-07-05 20:32
I tried myself on Edison. It looks like `libsharp` does not compile with the Intel compiler, which is default on Edison (/cc @mreineck ).

so if you switch to gnu:

    module unload PrgEnv-intel
    module load PrgEnv-gnu

it should work, I tested with a fresh Anaconda 2.3.0 Python 3.4.

Closing for now, reopen if still does not work.

**Comment by lpsinger** [comment] 2015-07-06 00:58
> I tried myself on Edison. It looks like libsharp does not compile with the Intel compiler, which is default on Edison (/cc @mreineck ).

Why did `pip install` succeed if libsharp failed to compile? Is there a build error that is going undetected?

**Comment by zonca** [comment] 2015-07-06 01:52
No actually in my case the build failed

**Comment by mreineck** [comment] 2015-07-06 08:37
On 07/05/15 22:32, Andrea Zonca wrote:
> I tried myself on Edison. It looks like `libsharp` does not compile with the Intel compiler, which is default on Edison (/cc @mreineck ).
>
There is no fundamental reason why icpc should not be able to compile
libsharp. Could you please report compiler version and detailed output
... I don't have ab account on Edison.

**Comment by cmbant** [comment] 2015-07-06 08:39
Actually I was using the gnu env. Here's the -v output

```
aml1005@edison06:~> pip install -v healpy
Collecting healpy
  Getting page https://pypi.python.org/simple/healpy/
  Starting new HTTPS connection (1): pypi.python.org
  "GET /simple/healpy/ HTTP/1.1" 200 717
  1 location(s) to search for versions of healpy:
  * https://pypi.python.org/simple/healpy/
  Getting page https://pypi.python.org/simple/healpy/
  Analyzing links from page https://pypi.python.org/simple/healpy/
    Found link https://pypi.python.org/packages/source/h/healpy/healpy-1.0.tar.gz#md5=f5dfd1e195568a2a767368ac78e4d422 (from https://pypi.python.org/simple/healpy/), version: 1.0
    Found link https://pypi.python.org/packages/source/h/healpy/healpy-1.1.tar.gz#md5=c193c0dff00ce702c4fbcd3207425843 (from https://pypi.python.org/simple/healpy/), version: 1.1
    Found link https://pypi.python.org/packages/source/h/healpy/healpy-1.6.0.tar.gz#md5=4f4df12950cf70f9723cab077c5f8a32 (from https://pypi.python.org/simple/healpy/), version: 1.6.0
    Found link https://pypi.python.org/packages/source/h/healpy/healpy-1.6.1.tar.gz#md5=9795befee883793c41b18f40797516f8 (from https://pypi.python.org/simple/healpy/), version: 1.6.1
    Found link https://pypi.python.org/packages/source/h/healpy/healpy-1.6.2.tar.gz#md5=f532ee927bb1fbe170b62b2fc95b3c2a (from https://pypi.python.org/simple/healpy/), version: 1.6.2
    Found link https://pypi.python.org/packages/source/h/healpy/healpy-1.6.3.tar.gz#md5=60152b75ee6e19b15e73ca21a3c4ddde (from https://pypi.python.org/simple/healpy/), version: 1.6.3
    Found link https://pypi.python.org/packages/source/h/healpy/healpy-1.7.0.tar.gz#md5=5ced7849ce3c9b0abb80ede8e2bbb926 (from https://pypi.python.org/simple/healpy/), version: 1.7.0
    Found link https://pypi.python.org/packages/source/h/healpy/healpy-1.7.1.tar.gz#md5=e6558e2b1807e3d4d8549b4a851fbb88 (from https://pypi.python.org/simple/healpy/), version: 1.7.1
    Found link https://pypi.python.org/packages/source/h/healpy/healpy-1.7.2.tar.gz#md5=1ee77a2a01077e933073ea5e7259dd9f (from https://pypi.python.org/simple/healpy/), version: 1.7.2
    Found link https://pypi.python.org/packages/source/h/healpy/healpy-1.7.3.tar.gz#md5=f52d673f872587eb0c52bb8f5393c95a (from https://pypi.python.org/simple/healpy/), version: 1.7.3
    Found link https://pypi.python.org/packages/source/h/healpy/healpy-1.7.4.tar.gz#md5=bfe12117fe276c05ecf75afe22f1c000 (from https://pypi.python.org/simple/healpy/), version: 1.7.4
    Found link https://pypi.python.org/packages/source/h/healpy/healpy-1.8.0.tar.gz#md5=c7f13d251d1cade9882adeadd46bd0e4 (from https://pypi.python.org/simple/healpy/), version: 1.8.0
    Found link https://pypi.python.org/packages/source/h/healpy/healpy-1.8.1.tar.gz#md5=1d1bccccea407eda4c366440ac09a3d7 (from https://pypi.python.org/simple/healpy/), version: 1.8.1
    Found link https://pypi.python.org/packages/source/h/healpy/healpy-1.8.2.tar.gz#md5=b7a12c3557b502dc5c2175cea691dac3 (from https://pypi.python.org/simple/healpy/), version: 1.8.2
    Found link https://pypi.python.org/packages/source/h/healpy/healpy-1.8.3.tar.gz#md5=741609c94ede96703fa802adc3715b39 (from https://pypi.python.org/simple/healpy/), version: 1.8.3
    Found link https://pypi.python.org/packages/source/h/healpy/healpy-1.8.4.tar.gz#md5=d99576e843a3f3aa0834fed0524b9981 (from https://pypi.python.org/simple/healpy/), version: 1.8.4
    Found link https://pypi.python.org/packages/source/h/healpy/healpy-1.8.5.tar.gz#md5=fe6c3a8e89fac5887c4a0e49cb9c5a82 (from https://pypi.python.org/simple/healpy/), version: 1.8.5
    Found link https://pypi.python.org/packages/source/h/healpy/healpy-1.8.6.tar.gz#md5=2bae5edd82b578891278ad1e3786dff9 (from https://pypi.python.org/simple/healpy/), version: 1.8.6
    Found link https://pypi.python.org/packages/source/h/healpy/healpy-github-devel.tar.gz#md5=94ad2a5469e5533ca73c2bb490243b41 (from https://pypi.python.org/simple/healpy/), version: github-devel
  Using version 1.8.6 (newest of versions: 1.8.6, 1.8.5, 1.8.4, 1.8.3, 1.8.2, 1.8.1, 1.8.0, 1.7.4, 1.7.3, 1.7.2, 1.7.1, 1.7.0, 1.6.3, 1.6.2, 1.6.1, 1.6.0, 1.1, 1.0)
Requirement already satisfied (use --upgrade to upgrade): matplotlib in ./anaconda/lib/python2.7/site-packages (from healpy)
Requirement already satisfied (use --upgrade to upgrade): six in ./anaconda/lib/python2.7/site-packages (from healpy)
Requirement already satisfied (use --upgrade to upgrade): astropy in ./anaconda/lib/python2.7/site-packages (from healpy)
Requirement already satisfied (use --upgrade to upgrade): numpy in ./anaconda/lib/python2.7/site-packages (from healpy)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in ./anaconda/lib/python2.7/site-packages (from matplotlib->healpy)
Requirement already satisfied (use --upgrade to upgrade): pytz in ./anaconda/lib/python2.7/site-packages (from matplotlib->healpy)
Requirement already satisfied (use --upgrade to upgrade): pyparsing>=1.5.6 in ./anaconda/lib/python2.7/site-packages (from matplotlib->healpy)
Requirement already satisfied (use --upgrade to upgrade): nose>=0.11.1 in ./anaconda/lib/python2.7/site-packages (from matplotlib->healpy)
Requirement already satisfied (use --upgrade to upgrade): mock in ./anaconda/lib/python2.7/site-packages (from matplotlib->healpy)
Installing collected packages: healpy

Successfully installed healpy-1.8.6
Cleaning up...
aml1005@edison06:~> ipython
Python 2.7.10 |Anaconda 2.3.0 (64-bit)| (default, May 28 2015, 17:02:03)
Type "copyright", "credits" or "license" for more information.

IPython 3.2.0 -- An enhanced Interactive Python.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import healpy
/global/homes/a/aml1005/anaconda/lib/python2.7/site-packages/healpy/sphtfunc.py:42: UserWarning: Warning: cannot import _sphtools module
  warnings.warn('Warning: cannot import _sphtools module')
/global/homes/a/aml1005/anaconda/lib/python2.7/site-packages/healpy/__init__.py:57: UserWarning: Warning: cannot import query disc module
  warnings.warn('Warning: cannot import query disc module')
/global/homes/a/aml1005/anaconda/lib/python2.7/site-packages/healpy/__init__.py:61: UserWarning: Warning: cannot import pixelfunc module
  warnings.warn('Warning: cannot import pixelfunc module')
/global/homes/a/aml1005/anaconda/lib/python2.7/site-packages/healpy/__init__.py:68: UserWarning: Warning: cannot import _sphtools module
  warnings.warn('Warning: cannot import _sphtools module')

In [2]: exit()
aml1005@edison06:~> cc --version
gcc (GCC) 4.9.2 20141030 (Cray Inc.)
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
aml1005@edison06:~> which pip
/global/homes/a/aml1005/anaconda/bin/pip
```

I'm using bash, with the following in .bashrc.ext

```
module unload darshan
module unload ipython
module unload python
module swap PrgEnv-intel PrgEnv-gnu
export PATH=/global/homes/a/aml1005/anaconda/bin:$PATH
export PYTHONPATH=
```

**Comment by cmbant** [comment] 2015-07-07 09:40
Btw, if I install from the git source, the installation actually seems to do something (lots of C files get compiled), but the end result, in terms of ipython not being able to load healpy, is the almost the same. A python 2.7 specific issue? (btw, as a user I can't reopen the issue myself)

An install recipe that did eventually work for me is
```
pip install --install-option="--home=/home/some/healpy" healpy
```
then (order very important) in .bashrc.ext (or equivalently in .cshrc.ext)

```
module load python
export PYTHONPATH=$PYTHONPATH:/home/some/healpy/lib/python
```

Suggests to me some kind of path issue with default install?

**Comment by zonca** [comment] 2015-07-07 19:49
I'm sorry, I don't understand what is the issue based on the symptoms you explained and I cannot reproduce the issue, so I'll close this.

**Closed by zonca** 2015-07-07 19:49 UTC
